05-lection/modal
js-tasks-ru/htmlcss-20210409_anosov-te pull request #12
Opened 2021-05-08 13:53 UTC by timuranosov

**- Finished modal window**

2021-05-08 13:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-08 15:54 UTC, GSemikozov requested changes

2021-05-08 15:54 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal-cross {
наименование класса не вписывается по БЭМ, может - `.modal__cross`?

2021-05-08 19:05 UTC, timuranosov commented on 05-lection3/02-modal/modal.css
> +.modal-cross {
**Resolved**

2021-05-10 14:10 UTC, GSemikozov approved these changes

2021-05-10 14:10 UTC, merged