06-lection/avatar
js-tasks-ru/htmlcss-20210409_anosov-te pull request #13
Opened 2021-05-08 20:24 UTC by timuranosov

**Finished avatar**

2021-05-08 20:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-10 14:14 UTC, GSemikozov requested changes

2021-05-10 14:14 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    object-fit: cover;
проверил верстку в codepen на примере различных картинок - данной реализации точно будет недостаточно, советую перепроверить ;)

2021-05-10 14:39 UTC, timuranosov commented on 06-lection4/01-avatar/avatar.css
> +    object-fit: cover;
**Resolved**

2021-05-10 16:56 UTC, GSemikozov requested changes

2021-05-10 16:56 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    object-fit: cover;
и все-таки - блоку надо задать фиксированные ширину и высоту, иначе ширина и высота блока будут = 0, поскольку картинка, позиционированная через absolute, выпадает из общего потока документа и никак не растягивает своего родителя.
https://codepen.io/hermansemykozov/pen/RwpWbZj

2021-05-10 18:26 UTC, timuranosov commented on 06-lection4/01-avatar/avatar.css
> +    object-fit: cover;
**Resolved**

2021-05-10 18:41 UTC, GSemikozov approved these changes

2021-05-10 18:42 UTC, merged