03-lection1/page
js-tasks-ru/htmlcss-20210409_anosov-te pull request #2
Opened 2021-04-17 13:22 UTC by timuranosov

**Finished layout**

2021-04-17 13:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-04-18 16:06 UTC, GSemikozov requested changes

2021-04-18 16:06 UTC, GSemikozov commented on components/header/header.css
> +    font-family: Inter, sans-serif;
кстати, советую обратить внимание, что этот шрифт у нас еще не подключен

2021-04-18 16:06 UTC, GSemikozov commented on components/header/header.css
> +    color: var(--black);
в качестве рекомендации следованию семантическому подходу именования переменных что в итоге упростит возможность создания темизации - лучше создать отдельную переменную для `primary-text-color` и переиспользовать ее

2021-04-18 16:06 UTC, GSemikozov commented on components/footer/footer.css
> +.footer__h2 {
такой вариант именования допустим, но - менее универсален, например что если мы в разметке захотим использовать заголовок другого уровня или вместо параграфа обычный div? Тогда классы типа footer__title и footer__text будут более подходящими

2021-04-19 14:02 UTC, timuranosov commented on components/header/header.css
> +    font-family: Inter, sans-serif;
Теперь подключил шрифт точно так же, как и подключен Roboto, других способов пока особо и не знаю.
**Resolved**

2021-04-19 14:02 UTC, timuranosov commented on components/header/header.css
> +    color: var(--black);
**Resolved**

2021-04-19 14:02 UTC, timuranosov commented on components/footer/footer.css
> +.footer__h2 {
**Resolved**

2021-04-19 14:58 UTC, GSemikozov commented on components/header/header.css
> +    font-family: Inter, sans-serif;
все правильно👍

2021-04-19 15:00 UTC, GSemikozov approved these changes

2021-04-19 15:00 UTC, merged