04-lection/skeleton
js-tasks-ru/htmlcss-20210409_anosov-te pull request #7
Opened 2021-04-22 10:53 UTC by timuranosov

**Finished skeleton**

2021-04-22 10:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-04-24 11:52 UTC, GSemikozov requested changes

2021-04-24 11:52 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +            <div class="skeleton__header__container">
опять эти назойливые "внучатых" элементы - надо поправить :)

2021-04-24 11:52 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
не стоит жестко фиксировать размеры - наши блоки должны быть адаптивными, поскольку могут встраиваться в разные гриды - где-то это будет ширина в 600px, а где-то - вообще на всю страницу

2021-04-24 11:52 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 529px;
ширину можем задать в процентах - важно для адаптивности (что будет если сузить размер нашего экрана постепенно до 320px?)

2021-04-24 17:51 UTC, timuranosov commented on 04-lection2/02-skeleton/index.html
> +            <div class="skeleton__header__container">
@GSemikozov **resolved**

2021-04-24 17:51 UTC, timuranosov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
@GSemikozov **resolved**

2021-04-24 17:51 UTC, timuranosov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 529px;
@GSemikozov **resolved**

2021-04-25 08:55 UTC, GSemikozov approved these changes

2021-04-25 08:55 UTC, merged