05-lection/calendar
js-tasks-ru/htmlcss-20210409_anosov-te pull request #9
Opened 2021-04-25 15:15 UTC by timuranosov

**Added calendar**

2021-04-25 15:15 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-04-25 18:40 UTC, GSemikozov requested changes

2021-04-25 18:40 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item_semi-active {
полу-активный? :)

2021-04-25 18:40 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item_day {
модификатор или элемент? И в том и в другом случае запись будет неверная) для модификатора будет неподходящим имя (по названию модификатора должно быть понятно КАК он модифицирует), а для элемента стоило бы указывать класс вот так `.calendar__item-day` или так `.calendar__day`

2021-04-26 20:13 UTC, timuranosov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item_semi-active {
**Resolved**

2021-04-26 20:13 UTC, timuranosov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item_day {
**Resolved**

2021-04-27 08:49 UTC, GSemikozov approved these changes

2021-04-27 08:49 UTC, merged